export default {
	//------------------------------------
	// Basic
	replies: "{# [1:reply][?:replies]}",
	topics: "{# [1:topic][?:topics]}",
	posts: "{# [1:post][?:posts]}",
	quote: "Quote",
	post_options: "Post Options",
	end_of_forum: "You've reached the end of this forum.",
	cancel: "Cancel",
	post_action: "Post",
	save: "Save",
	confirm: "Confirm",
	yes: "Yes",
	no: "No",
	add: "Add",
	report: "Report",
	show: "Show",
	hide: "Hide",
	replace: "Replace",
	load_earlier: "Load Earlier Posts",
	write_reply: "Write a reply...",
	unread_posts: "Unread Posts",
	your_profile: "Go to your profile",
	settings: "Account Settings",
	sign_out: "Sign Out",
	notification_settings: "Notification Settings",
	disabled_notification: "This site doesn't allow you to change this.",
	legal_notices: "Legal Notices",
	edit_profile: "Edit Profile",
	offline: "{{siteName}} is offline",
	home: "Home",
	browse: "Browse",
	our_picks: "Our Picks",
	new_content: "New For You",
	active_users: "Active Now",
	popular_contributors: "Top Users This Week",
	x_more: "{# [?:more]}",
	no_users_online: "No users online right now",
	x_guests_online: "{# [1:guest][?:guests] online}",
	activity_replied: "{{user}} replied to {{article}}",
	activity_commented: "{{user}} commented on {{article}}",
	activity_reviewed: "{{user}} reviewed {{article}}",
	activity_posted_item: "{{user}} posted {{article}}",
	activity_generic: "A user posted",
	login_prompt: "Sign in now to get the most out of {{siteName}}!",
	login_register_prompt: "Register or sign in now to get the most out of {{siteName}}!",
	login_prompt_comment: "Add your own thoughts! Sign in now to reply.",
	login_register_prompt_comment: "Add your own thoughts! Register or sign in now to reply.",
	register: "Register",
	sign_in: "Sign In",
	home_view_error: "Sorry, there was a problem loading your home view",
	topic_view_error: "Sorry, we couldn't load this topic",
	no_topics: "There are no topics in this forum",
	forum_requires_password: "This is a password-protected forum",
	enter_password: "Enter Password",
	password: "Password",
	go: "Go",
	error: "Error",
	error_remove_reaction: "Sorry, there was an error removing the reaction from this post.",
	error_reacting: "Sorry, there was an error reacting to this post.",
	error_following: "Sorry, there was a problem following this content",
	error_unfollowing: "Sorry, there was a problem unfollowing this content",
	ok: "OK",
	cant_show_reactions: "Sorry, we couldn't load reactions for this content.",
	editor_quote_line_with_time: "{{date}}, {{username}} said:",
	editor_quote_line: "{{username}} said:",
	ignoring_user: "You are ignoring this user.",
	pagination: "{{from}} of {{to}}",
	insert: "Insert",
	insert_into_post: "Insert into post",
	delete_image: "Delete attachment",
	cancel_upload: "Cancel upload",
	attachment_options: "Attachment Options",
	no_matching_members: "No matching members",
	rep: "rep",
	no_rep_this_week: "No-one has received reputation this week.",
	list_two: "{{one}} and {{two}}",
	list_three: "{{one}}, {{two}} and {{three}}",
	take_photo: "Take Photo",
	camera_roll: "Choose from Camera Roll",
	failed: "Failed",
	error_loading: "Sorry, there was a problem loading this content.",
	try_again: "Try Again",
	load_earlier_comments: "Load Earlier Comments",
	unread_comments: "Unread Replies",
	order_start_unread: "Start at first unread comment",
	order_start_first: "Start at the first comment",
	order_start_last: "Start at the most recent comment",
	content_view_desc: "Determines where you are taken when tapping into content. Applies only to this device.",
	error_marking_read: "Couldn't mark as read",
	error_marking_read_desc: "There was an error marking this as read",
	someones_x: "{{name}}'s {{thing}}",
	no_results: "Nothing to show",
	who_reacted: "Who Reacted",
	account_settings: "Account Settings",
	reply_screen: "Reply",
	tab_home: "Home",
	tab_search: "Search",
	tab_streams: "Streams",
	tab_notifications: "Notifications",
	tab_user: "You",
	tab_signin: "Sign In/Up",
	confirm_logout: "Are you sure you want to log out on this device?",
	submitting: "Submitting",
	discard: "Discard",
	stay_here: "Stay Here",
	upload_in_progress: "Uploads In Progress",
	upload_in_progress_desc: "Please wait until your uploaded images have finished processing, then submit again.",
	quoting_x: "Quoting {{name}}:",
	your_reply: "Your Reply",
	started_by_x: "Started by {{name}}",
	cannot_reply_with_info: "You cannot reply (tap for details)",
	copy_permalink: "Copy Permalink",
	copied_permalink: "Permalink copied!",
	ignore: "Ignore {{name}}",
	unignore: "Stop ignoring {{name}}",
	ignore_options: "Ignore {{name}}",
	error_ignoring_member: "Sorry, there was an problem ignoring this member",
	error_ignore_type: "Invalid ignore type",
	error_ignore_member: "This member cannot be ignored.",
	error_ignore_no_self: "You can't ignore yourself.",

	//------------------------------------
	// Time stuff
	seconds: "{# [1:second][?:seconds]}",
	minutes: "{# [1:minute][?:minutes]}",
	hours: "{# [1:hour][?:hours]}",
	days: "{# [1:day][?:days]}",
	weeks: "{# [1:week][?:weeks]}",
	months: "{# [1:month][?:months]}",
	years: "{# [1:year][?:years]}",
	seconds_short: "{#[?:s]}",
	minutes_short: "{#[?:m]}",
	hours_short: "{#[?:h]}",
	days_short: "{#[?:d]}",
	weeks_short: "{#[?:w]}",
	months_short: "{#[?:mo]}",
	years_short: "{#[?:y]}",
	time_future: "in {{val}}",
	time_past: "{{val}} ago",

	//------------------------------------
	// Editor
	link_url: "Link URL",
	link_text: "Link text (optional)",
	invalid_link: "Invalid Link",
	invalid_link_desc: "The URL you entered isn't valid. Please check and try again.",
	error_upload_type: "You can't upload images of this type.",
	error_upload_space: "You don't have enough space to upload this image.",
	error_upload_other: "There was a problem uploading this image.",

	//------------------------------------
	// Custom fields
	no_address: "No address",
	no_color: "No color",
	no_date: "No date",
	no_email: "No email",
	no_selection: "No selection",
	no_member: "No member",
	no_value: "No value",
	not_available: "Not available",
	no_url: "No URL",

	//------------------------------------
	// Itme statuses
	status_pinned: "Pinned",
	status_hidden: "Hidden",
	status_hidden_desc: "This post is only visible to moderators",
	status_deleted: "Deleted",
	status_deleted_desc: "This post is pending deletion",
	status_unapproved: "Pending",
	status_unapproved_desc: "This post is pending approval by a moderator",
	status_hot: "Hot",
	status_featured: "Featured",
	status_locked: "Locked",
	status_archived: "Archived",

	//------------------------------------
	// Sharing
	share: "Share",
	error_sharing_content: "Sorry, there was a problem sharing this content.",
	share_x_on_x_at_x: '{{name}}\'s {{thing}} in "{{title}}" at {{site}}',
	share_x: "Sharing {{name}}'s {{thing}}",

	//------------------------------------
	// Profiles
	followed_member: "You're now following {{name}}",
	unfollowed_member: "You've unfollowed {{name}}",
	profile_content_count: "Content Count",
	profile_reputation: "Reputation",
	profile_followers: "Followers",
	profile_overview: "Overview",
	profile_content: "Content",
	basic_information: "Basic Information",
	joined: "Joined",
	email_address: "Email Address",
	end_of_profile_content: "No more content to show",
	profile_error: "There was a problem loading this profile",

	//------------------------------------
	// Login
	username: "Username",
	password: "Password",
	forgot_password: "Forgot Password?",
	sign_in_anon: "Sign in anonymously",
	sign_in_with_social: "Or sign in with one of these services",

	//------------------------------------
	// Search
	search_site: "Search {{siteName}}",
	loading: "Loading",
	no_recent_searches: "No recent searches",
	error_searching: "There was an error completing this search.",
	no_results: "There were no matches for this search.",
	no_results_in_x: "No {{type}} matched this search.",
	see_all: "See All",
	name_replied: "{{name}} replied:",
	item_in_container: "{{item}} in {{container}}",
	in_container: "In {{container}}",
	overview: "Overview",
	top_content: "Top Content",
	top_members: "Top Members",
	recent_searches: "Recent Searches",
	content: "Content",

	//------------------------------------
	// Topics
	forums: "Forums",
	create_new_topic: "Create New Topic",
	topics_title: "Topics",
	subforums_title: "Subforums",
	no_forum: "The forum does not exist.",
	no_topic: "The topic does not exist.",
	incorrect_forum_password: "The password to this forum wasn't provided",
	no_post: "The post does not exist.",
	invalid_topic: "The topic couldn't be loaded.",
	not_question: "This topic cannot be voted upon.",
	cannot_vote: "You cannot vote on this question.",
	error_voting_question: "There was a problem voting on this question.",
	replace_best_answer_title: "Confirm",
	replace_best_answer_text: "Are you sure you want to replace the current Best Answer with this one?",
	question_asked_by: "Question asked by {{name}}",
	this_is_best_answer: "Best answer to this question",
	all_topics: "All Topics",
	all_topics_desc: "Showing all topics from all forums",
	create_topic: "Create Topic",
	confirm_discard_topic: "Are you sure you want to discard this topic without posting?",
	confirm_discard_post: "Are you sure you want to discard this reply without posting?",
	title_required: "Title Required",
	title_required_desc: "You must enter a topic title.",
	post_required: "Post Required",
	post_required_desc: "You must enter a post.",
	error_posting_topic: "Sorry, there was an error posting this topic. ",
	error_posting_post: "Sorry, there was an error posting this reply. ",
	topic_title: "Topic Title",
	post_title: "Post",
	topic_cannot_reply: "Cannot Reply",
	topic_locked_can_comment: "Locked, but you can reply...",
	topic_poll_can_comment: "Poll-only, but you can reply...",
	topic_locked_cannot_comment: "You don't have permission to reply because this topic is locked.",
	topic_restricted_cannot_comment: "Your account is currently restricted from posting.",
	topic_unacknowledged_warning_cannot_post: "You have received a warning that you must acknowledge before being able to post.",
	topic_member_exceeded_posts_per_day: "You have reached the maximum number posts you can make per day.",

	//------------------------------------
	// Polls
	votes: "{# [1:vote][?:votes]}",
	votes_nonum: "{!# [1:vote][?:votes]}",
	poll_closed: "Voting has ended",
	poll_closes_date: "Poll closes {{date}}",
	poll_view: "View Poll",
	poll_view_results: "View Results",
	poll_view_and_vote: "See Questions & Vote",
	poll_you_voted: "You've voted",
	poll_prefix: "Poll:",
	poll_question_number: "Question {{number}}",
	poll_multiple_choice: "This question is multiple choice",
	poll_view_confirm: "By viewing the poll results, you will forfeit the ability to vote.",
	poll_no_permission: "This topic has a poll, but you do not have permission to vote, or see the results.",
	poll_submit_votes: "Submit Votes",
	poll_change_vote: "Change My Vote",
	poll_update_vote: "Update My Vote",

	//------------------------------------
	// Tags
	tags_min_max: "Choose up to {# [1:tag][?:tags]} (but at least {{min}})",
	tags_min: "Choose at least {# [1:tag][?:tags]}",
	tags_min_error: "You must choose at least {# [1:tag][?:tags]}",
	tags_max: "Choose up to {# [1:tag][?:tags]}",
	tags_max_error: "A maximum of {# [1:tag is][?:tags are]} allowed",
	tags_len_min_max: "Tags must be between {{min}} and {# [1:tag][?:chracters]} long",
	tags_len_min: "Tags must be at least {# [1:character][?:characters]} long",
	tags_len_max: "Tags can be up to {# [1:character][?:characters]} long",
	manage_tags: "Manage Tags",
	enter_tag: "Enter tag",
	tags: "Tags",
	tag_suggestions: "Suggestions",
	too_many_tags: "Too Many Tags",
	too_few_tags: "Not Enough Tags",

	//------------------------------------
	// Notification list
	no_more_notifications: "No more notifications right now",
	notifications_unread: "Unread",
	notifications_read: "Already Seen",
	no_notifications: "You have no notifications",

	//------------------------------------
	// Notification settings
	notification_instructions: "You have not yet granted notification permissions on this device.",
	notification_instructions_ios: "To check permissions, go to the Settings app from your home screen, then tap Notifications.",
	notification_instructions_android: "To check permissions, go to the Settings app on your Android device, then tap Apps & Notifications.",
	notification_android_extra: "Notifications you receive are also configurable in your Android system settings.",
	notification_android_extra_desc: "You'll only receive notifications if you have granted permission both in Android settings and on this screen.",
	email_notification: "Email notification",
	email_notification_desc: "Email notifications will be sent to {{email}}",
	notification_types: "Notification Types",
	notification_both: "Mobile app & notification list",
	notification_inline: "Notification list only",
	notification_none: "No app or list notifications",
	notification_type_push: "Mobile App",
	notification_type_email: "Email",
	notification_type_inline: "Notification List",
	notification_type_none: "None",
	notification_inline_only: "Show in Notification List",

	//------------------------------------
	// Streams
	switch_stream: "Switch Stream",
	past_hour: "Past Hour",
	yesterday: "Yesterday",
	today: "Today",
	last_week: "Last Week",
	earlier: "Earlier",
	all_activity: "All Activity",
	stream_error: "Error loading this stream",

	//------------------------------------
	// Follows
	x_follow_this: "{# [1:member follows][?:members follow] this}",
	follow_immediate: "A notification when new content is posted",
	follow_weekly: "A weekly email with new content",
	follow_daily: "A daily email with the new content",
	follow_none: "Don't send me a notification",
	follow_anon: "Follow anonymously",
	follow_freq: "Follow frequency",
	follow_privacy: "Privacy options",
	follow: "Follow",
	follow_save: "Save Preference",
	unfollow: "Unfollow",
	error_select_follow_option: "Select a follow option",
	no_followers: "{{name}} has no followers yet",

	//------------------------------------
	// Reports
	reporting_x_in_x: "You are reporting {thing} in {item} to the moderators of {site_name}.",
	revoke_report_x_in_x: "You have already reported {thing} in {item}. You may revoke your report if you wish.",
	reporting_x: "You are reporting {item} to the moderators of {site_name}.",
	revoke_report_x: "You have already reported {item}. You may revoke your report if you wish.",
	error_must_select_report_reason: "Please select a report reason.",
	error_already_reported: "You have already reported this content.",
	error_report_failed: "Sorry, it wasn't possible to report this content right now.",
	error_cannot_report: "Sorry, you can't report this content right now.",
	error_revoke_failed: "Sorry, you can't revoke your report right now.",
	thanks_for_report: "Thanks for your report!",
	revoke_success: "Your report was revoked.",
	sending_report: "Sending Report...",
	send_report: "Submit Report",
	sending_revoke: "Revoking Report...",
	send_revoke: "Revoke Report",
	choose_reason: "What's Wrong?",
	report_reason: "Reason",
	additional_report_info: "Additional Information",
	no_additional_info: "No additional information provided",
	report_info_placeholder: "Optionally include additional information with your report...",
	report_unknown: "(Unknown reason)",
	report_content_screen: "Report Content",

	//------------------------------------
	// Notification settings
	notification_group_core: "General",
	notifications__club_invitation: "Invitations to join a club",
	notifications__club_response: "Responses to my club join requests",
	notifications__club_request: "Requests to join clubs I lead",
	notifications__club_join: "New users in clubs I lead",
	notifications__unapproved_club: "Clubs that are created",
	notifications__new_content: "New items in areas I follow",
	notifications__new_comment: "Comments on content I follow",
	notifications__new_review: "Reviews on content I follow",
	notifications__follower_content: "New content by users I follow",
	notifications__quote: "Content I'm quoted in",
	notifications__mention: "Content I'm mentioned in",
	notifications__embed: "Links to my content by others",
	notifications__new_likes_rep: "Reputation I'm given by others",
	notifications__new_likes_like: "'Likes' I'm given by others",
	notifications__warning_mods: "Warnings issued by moderators",
	notifications__report_center: "Reports submitted by users",
	notifications__automatic_moderation: "Content that's automatically moderated",
	notifications__unapproved_content: "New content that needs approval",
	notifications__new_private_message: "Messages I receive",
	notifications__private_message_added: "Messages I'm added to",
	notifications__member_follow: "Follows by other users",
	notifications__profile_comment: "Posts on my profile by others",
	notifications__profile_reply: "Replies to my status updates",
	notifications__new_status: "Status updates by users I follow",

	//------------------------------------
	// Legal
	legal_terms: "Terms & Rules",
	legal_privacy: "Privacy Policy",
	legal_guidelines: "Site Guidelines",
	third_party_licenses: "Third-party Licenses",
	legal_app_privacy: "Mobile App Privacy Policy"
};
